version: '3.1'

services:
  ## optionally, this nginx setup can be used for scaling a dashboard.
  ## to use, uncomment the lines below, and change app ports from "8000:8000"
  ## to just "8000". It will be testable on localhost:80
  #nginx:
  #  image: nginx:latest
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #  depends_on:
  #    - app
  #  ports:
  #    - "80:80"

  app:
    build: .
    restart: always
    ports:
      - "8000:8000"
