name: covid_19_eda
channels:
- conda-forge
- defaults
- anaconda
dependencies:
- python=3.6
- jupyter=1.0.0
- matplotlib=3.1.1
- pandas=0.25.1
- scipy=1.3.1
- seaborn=0.9.0
- altair=4.1.0
- bokeh==2.0.1
- vega
